name       : glibmm-2.68
version    : 2.74.1
release    : 2
source     :
    - https://download.gnome.org/sources/glibmm/2.74/glibmm-2.74.1.tar.xz : 1b78fb9d282a76b322866d5e2eeff288a25dec9c9464d85cd34969cd40cc1999
license    : GPL-2.0-only
component  : desktop.gtk
summary    : C++ bindings to GLib (2.68 ABI)
description: |
    C++ bindings to GLib (2.68 ABI)
builddeps  :
    - pkgconfig(sigc++-3.0)
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
